feat: 新增adjust命令和checklang

diff --git a/posture b/posture
--- a/posture
+++ b/posture
@@ -3,10 +3,21 @@ currentDir=$(pwd)
 . $currentDir/include/function.sh
 COMMAND=$1
 
+checklang
+if [ $? -ne 0 ]; then
+    echo "configuration set error"
+    exit 1
+fi
+
 if [ "${COMMAND}" == "hooking" ]; then
   hooking $currentDir
 fi
 
-if [ "${COMMAND}" == "init" ]; then
-  init
+if [ "${COMMAND}" == "adjust" ]; then
+  adjust
+fi
+
+if [ "${COMMAND}" == "info" ]; then
+  echo "The list of information"
+  echo "> lang = ${lang}"
 fi
